In [2]:
if 1<2:
    print("oops!")
    print("xyz")
else:
    print("this is what we expect")
    print("abc")

oops!
xyz


In [3]:
y=5 ; x=3

In [4]:
y

5

In [5]:
x

3

In [9]:
y = x + \
        3

In [10]:
y

6

In [22]:
s = """This a ' doesn't end
... this continues"""

In [23]:
s

"This a ' doesn't end\nthis continues"

In [18]:
d= """Note that a ' doesn't end
... this string and that it spans two lines"""

In [19]:
d

"Note that a ' doesn't end\nthis string and that it spans two lines"

In [24]:
print(d)

Note that a ' doesn't end
this string and that it spans two lines


In [25]:
print("This spans \n two lines")

This spans 
 two lines


In [26]:
import numpy as np

In [27]:
print(type(np))

<class 'module'>


In [28]:
print(type(np.pi))
x=np.pi
print(type(x))

<class 'float'>
<class 'float'>


In [29]:
print(type(np.cos))

<class 'numpy.ufunc'>


In [30]:
x=np.linspace(0,5,8)
print(x)

[0.         0.71428571 1.42857143 2.14285714 2.85714286 3.57142857
 4.28571429 5.        ]


In [31]:
print(type(x))

<class 'numpy.ndarray'>


In [32]:
np.max(x)

5.0

In [34]:
x.max()

5.0

In [35]:
L =[0,1,2]

In [36]:
type(L)

list

In [37]:
L.append(4)

In [38]:
L

[0, 1, 2, 4]

In [39]:
x=3.4

In [40]:
2*x

6.8

In [41]:
x= 'string'

In [42]:
2*x

'stringstring'

In [43]:
x=[4,5,6]

In [44]:
x*2

[4, 5, 6, 4, 5, 6]

In [45]:
L =[4,5,6]

In [46]:
L[0:]

[4, 5, 6]

In [47]:
L[1]

5

In [49]:
L=[5,2.3,'abc',[4,'b'],np.cos]
for i in L:
        print(i)

5
2.3
abc
[4, 'b']
<ufunc 'cos'>


In [58]:
for index,value in enumerate(L):
    print('L[%s] is %16s %s' % (index,value,type(value)))
    print(index,value)

L[0] is                5 <class 'int'>
0 5
L[1] is              2.3 <class 'float'>
1 2.3
L[2] is              abc <class 'str'>
2 abc
L[3] is         [4, 'b'] <class 'list'>
3 [4, 'b']
L[4] is    <ufunc 'cos'> <class 'numpy.ufunc'>
4 <ufunc 'cos'>


In [59]:
for index in [-1, -2, -3, -4, -5]:
    print('L[%s] is %16s' % (index, L[index]))

L[-1] is    <ufunc 'cos'>
L[-2] is         [4, 'b']
L[-3] is              abc
L[-4] is              2.3
L[-5] is                5


In [61]:
print(L[index])

5


In [62]:
x=[4,5,6]

In [63]:
y=list(x)

In [64]:
y

[4, 5, 6]

In [65]:
y.append(9)

In [66]:
y

[4, 5, 6, 9]

In [67]:
x

[4, 5, 6]

In [71]:
x=3.4
y=x
y=y+1
y

4.4

In [72]:
x

3.4

In [73]:
id(x)
id(y)

1967846620400

In [74]:
id (x)

1967846620448

In [75]:
id(y)

1967846620400

In [76]:
s="string"
s2=s

In [77]:
id(s2)

1967804842312

In [78]:
id(s)

1967804842312

In [79]:
s="new strng"

In [80]:
id(s)

1967865638960

In [81]:
t=(4,5,6)

In [82]:
t[0]

4

In [83]:
t[0]=9

TypeError: 'tuple' object does not support item assignment

In [84]:
L=[0,5,2,23,4]

In [85]:
L

[0, 5, 2, 23, 4]

In [86]:
L[0]=44

In [87]:
L

[44, 5, 2, 23, 4]

In [89]:
for i in [3,7,'b']:
    print("i is now ", i)

i is now  3
i is now  7
i is now  b


In [90]:
range(7)

range(0, 7)

In [91]:
L=['a',8,12]

In [92]:
for i in range(len(L)):
    print("i = ",i," L[i]= ",L[i])

i =  0  L[i]=  a
i =  1  L[i]=  8
i =  2  L[i]=  12


In [93]:
range(2,20,3)

range(2, 20, 3)

In [94]:
np.linspace(2,20,7)

array([ 2.,  5.,  8., 11., 14., 17., 20.])

In [95]:
import os
print(os.getcwd())

C:\Users\yasha


In [98]:
"""
Sample script to print values of a function at a few points.
"""
import numpy as np

def f(x):
    """
    A quadratic function.
    """
    y = x**3 + 3
    return y

print("     x        f(x)")
for x in np.linspace(0,4,3):
    print("%8.3f  %8.3f" % (x, f(x)))

     x        f(x)
   0.000     3.000
   2.000    11.000
   4.000    67.000


In [99]:
f

<function __main__.f(x)>

In [100]:
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [103]:
import script2

In [104]:
script2.__name__

'script2'

In [105]:
script2.f(4)

17.0

In [106]:
script2.print_table()

     x        f(x)
   0.000     1.000
   2.000     5.000
   4.000    17.000


In [118]:
import script2

In [119]:
script2.print_table()

     x        f(x)
   0.000     1.000
   2.000     5.000
   4.000    17.000


In [120]:
from importlib import reload
reload(script2)

<module 'script2' from 'C:\\Users\\yasha\\script2.py'>

In [121]:
script2.print_table()

     x        f(x)
   0.000    10.000
   2.000    14.000
   4.000    26.000


In [122]:
import os, sys

In [123]:
os.getcwd()

'C:\\Users\\yasha'

In [124]:
os.getcwd


<function nt.getcwd()>

In [125]:
print(sys.path)

['', 'C:\\ProgramData\\Anaconda3\\python36.zip', 'C:\\ProgramData\\Anaconda3\\DLLs', 'C:\\ProgramData\\Anaconda3\\lib', 'C:\\ProgramData\\Anaconda3', 'C:\\Users\\yasha\\AppData\\Roaming\\Python\\Python36\\site-packages', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\yasha\\.ipython']


In [126]:
import junkname

ModuleNotFoundError: No module named 'junkname'

In [127]:
x =45.6

In [128]:
x

45.6

In [129]:
s= "the value  of x is %s" %x

In [130]:
s

'the value  of x is 45.6'

In [131]:
s= "the value  of x is %21.14e" %x

In [132]:
s

'the value  of x is  4.56000000000000e+01'

In [133]:
y =-.324
y

-0.324

In [134]:
s="Now x is %8.3f and y is %8.3f" %(x,y)

In [135]:
s

'Now x is   45.600 and y is   -0.324'

In [136]:
import pandas as pd
from pylab import *
df= pd.DataFrame(rand(10,5), columns=["A","B","C","D","E"])

In [137]:
df.ix[:,df.ix[0,:]<0.5]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


A         D         E
0  0.171991  0.371350  0.415514
1  0.989873  0.462922  0.656439
2  0.297890  0.630229  0.426770
3  0.836712  0.722807  0.365093
4  0.320153  0.641368  0.089778
5  0.994886  0.359281  0.777128
6  0.881209  0.396402  0.896776
7  0.329147  0.343049  0.744719
8  0.731536  0.248410  0.952481
9  0.632004  0.103668  0.065687

In [138]:
import pandas as pd
import string

In [139]:
spam_corpus=map(str.split, [ "buy viagra", "buy antibody" ])
print(spam_corpus)

In [140]:
unique_words = set([ word for doc in spam_corpus for word in doc ])
print(unique_words)

{'buy', 'antibody', 'viagra'}


In [141]:
word_counts = [ (word, map(lambda doc: doc.count(word), spam_corpus)) for word in unique_words ]
print(word_counts)

[('buy', <map object at 0x000001CA2F8564E0>), ('antibody', <map object at 0x000001CA2F93B080>), ('viagra', <map object at 0x000001CA2F93B0B8>)]


In [143]:
word_counts = [ (word, map(lambda doc: doc.count(word), spam_corpus)) for word in unique_words ]
print(word_counts)

[('buy', <map object at 0x000001CA2F9F79E8>), ('antibody', <map object at 0x000001CA2F9F7A20>), ('viagra', <map object at 0x000001CA2F9F7A58>)]


In [144]:
spam_bag_of_words = pd.DataFrame(dict(word_counts))
print(spam_bag_of_words)

TypeError: object of type 'map' has no len()

In [145]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
url = "http://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv"
dat = pd.read_csv(url)
results = smf.ols("Lottery ~ Literacy + np.log(Pop1831)", data=dat).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Lottery   R-squared:                       0.348
Model:                            OLS   Adj. R-squared:                  0.333
Method:                 Least Squares   F-statistic:                     22.20
Date:                Mon, 13 Apr 2020   Prob (F-statistic):           1.90e-08
Time:                        18:12:55   Log-Likelihood:                -379.82
No. Observations:                  86   AIC:                             765.6
Df Residuals:                      83   BIC:                             773.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         246.4341     35.233      6.995      0.000     176.358     316.510
Literacy           -0.4889      0.128     -3.832      0.000      -0.743      -0.235
np.log(Pop1831)   -31.3114      5.977     -5.239      0.000     -43.199     -19.424
==============================================================================
Omnibus:                        3.713   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.156   Jarque-Bera (JB):                3.394
Skew:                          -0.487   Prob(JB):                        0.183
Kurtosis:                       3.003   Cond. No.                         702.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [146]:
dat

Unnamed: 0  dept Region           Department  Crime_pers  Crime_prop  \
0            1     1      E                  Ain       28870       15890   
1            2     2      N                Aisne       26226        5521   
2            3     3      C               Allier       26747        7925   
3            4     4      E         Basses-Alpes       12935        7289   
4            5     5      E         Hautes-Alpes       17488        8174   
5            6     7      S              Ardeche        9474       10263   
6            7     8      N             Ardennes       35203        8847   
7            8     9      S               Ariege        6173        9597   
8            9    10      E                 Aube       19602        4086   
9           10    11      S                 Aude       15647       10431   
10          11    12      S              Aveyron        8236        6731   
11          12    13      S     Bouches-du-Rhone       13409        5291   
12          13    14      N             Calvados       17577        4500   
13          14    15      C               Cantal       18070       11645   
14          15    16      W             Charente       24964       13018   
15          16    17      W  Charente-Inferieure       18712        5357   
16          17    18      C                 Cher       21934       10503   
17          18    19      C              Correze       15262       12949   
18          19    21      E            Cote-d'Or       32256        9159   
19          20    22      W        Cotes-du-Nord       28607        7050   
20          21    23      C               Creuse       37014       20235   
21          22    24      W             Dordogne       21585       10237   
22          23    25      E                Doubs       11560        5914   
23          24    26      E                Drome       13396        7759   
24          25    27      N                 Eure       14795        4774   
25          26    28      C         Eure-et-Loir       21368        4016   
26          27    29      W            Finistere       29872        6842   
27          28    30      S                 Gard       13115        7990   
28          29    31      S        Haute-Garonne       18642        7204   
29          30    32      S                 Gers       18642       10486   
..         ...   ...    ...                  ...         ...         ...   
56          57    59      N                 Nord       26740        6175   
57          58    60      N                 Oise       28180        6659   
58          59    61      N                 Orne       28329        8248   
59          60    62      N        Pas-de-Calais       23101        4040   
60          61    63      C          Puy-de-Dome       17256       12141   
61          62    64      W      Basses-Pyrenees       16722        8533   
62          63    65      S      Hautes-Pyrenees       12223        9797   
63          64    66      S  Pyrenees-Orientales        6728        7632   
64          65    67      E             Bas-Rhin       12309        4920   
65          66    68      E            Haut-Rhin        7343        4915   
66          67    69      E                Rhone       18793        4504   
67          68    70      E          Haute-Saone       22339        7770   
68          69    71      E       Saone-et-Loire       28391       10708   
69          70    72      C               Sarthe       33913        8294   
70          71    75      N                Seine       13945        1368   
71          72    76      N     Seine-Inferieure       18355        2906   
72          73    77      N       Seine-et-Marne       22201        5786   
73          74    78      N        Seine-et-Oise       12477        3879   
74          75    79      W          Deux-Sevres       18400        6863   
75          76    80      N                Somme       33592        7144   
76          77    81      S                 Tarn    

In [147]:
data = {'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]} 
  
# Create DataFrame 
df = pd.DataFrame(data) 
  
# Print the output. 
df

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [148]:
# importing pandas as pd 
import pandas as pd 
  
# importing numpy as np 
import numpy as np 
  
# dictionary of lists 
dict = {'First Score':[100, 90, np.nan, 95], 
        'Second Score': [30, 45, 56, np.nan], 
        'Third Score':[np.nan, 40, 80, 98]} 
  
# creating a dataframe from dictionary 
df = pd.DataFrame(dict) 
  
# filling missing value using fillna()   
df.fillna(0)

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [149]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']], columns=['animal', 'name'])
pd.concat([df1, df4], axis=1)


letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

In [150]:
x = 4
print(x)       # Prints "3"
print(type(x)) # Prints "<class 'int'>"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1
print(x)  # Prints "5"
x *= 2
print(x)  # Prints "10"
y = 1.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "1.5 2.5 3.0 2.25"

4
<class 'int'>
5
3
8
16
5
10
<class 'float'>
1.5 2.5 3.0 2.25


In [151]:
def quicksort(array):
    if len(array) <= 1:
        return array
    pivot = array[len(array) // 2]
    left = [x for x in array if x < pivot]
    middle = [x for x in array if x == pivot]
    right = [x for x in array if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([4,5,3,1,2,10,9]))
# Prints "[1, 2, 3, 4, 5, 9, 10]"

[1, 2, 3, 4, 5, 9, 10]


In [152]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

1: dog
2: cat
3: fish


In [153]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


In [1]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [11]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a.shape)
print(a[[0,1,2],[0,1,0]])  # Prints "[1 4 5]"

(3, 2)
[1 4 5]


In [12]:

import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [13]:
print(a) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [17]:
print(a[np.arange(4), b])

[ 1  6  7 11]


In [18]:
a[np.arange(4), b] += 10

print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
